language: node_js
node_js:
  - "stable"
branches:
  only:
  - master
before_script:
  - npm run lint
after_success:
  - npm run coverage
  - npm version 1.0.${TRAVIS_BUILD_NUMBER}
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_AUTH_TOKEN
